networks:
    cake-generator-dev:
        driver: bridge
volumes:
    cake-generator-postgres-data:
        name: cake-generator-postgres-data
    cake-generator-recipes-data:
        name: cake-generator-recipes-data
    cake-generator-redis-data:
        name: cake-generator-redis-data

services:
    app:
        build:
            context: ./Docker/Dev
            dockerfile: Dockerfile
            args:
                - INSTALL_XDEBUG=${DOCKER_INSTALL_XDEBUG:-true}
                - USER_ID=${DOCKER_HOST_USER_ID:-1000}
        container_name: cake-generator-app-dev
        working_dir: /application
        volumes:
            - ./Docker/Dev/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./Docker/Dev/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
            - ./Docker/Dev/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
            - ./Docker/Dev/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
            - ./:/application
        ports:
            - ${DOCKER_APP_HOST_PORT:-63851}:80
            - "5173:5173"
        networks:
            - cake-generator-dev
        restart: unless-stopped
        depends_on:
            database:
                condition: service_healthy


    database:
        image: postgres:17-alpine
        container_name: cake-generator-db-dev
        environment:
            - POSTGRES_USER=example_user
            - POSTGRES_PASSWORD=example_password
            - POSTGRES_DB=example_db
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --dbname=${DB_DATABASE} --username=${DB_USERNAME} "]
            interval: 3s
            timeout: 3s
            retries: 5
        ports:
            - ${DOCKER_DATABASE_HOST_PORT:-63853}:5432
        volumes:
            - cake-generator-postgres-data:/var/lib/postgresql/data
        networks:
            - cake-generator-dev
        restart: unless-stopped

    recipes-db:
        image: mysql:8
        container_name: cake-generator-recipes-data
        environment:
            MYSQL_DATABASE: recipes_db
            MYSQL_USER: recipes_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "63855:3306"
        volumes:
            - cake-generator-recipes-data:/var/lib/mysql
        networks:
            - cake-generator-dev

    mailpit:
        image: axllent/mailpit:v1.24.0
        container_name: cake-generator-mailpit-dev
        ports:
            - ${DOCKER_MAILPIT_DASHBOARD_HOST_PORT:-63854}:8025
            - "1025:1025"
        networks:
            - cake-generator-dev
        restart: unless-stopped

    redis:
        image: redis:7.4-alpine
        container_name: test-redis-dev
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-63852}:6379
        volumes:
            - cake-generator-redis-data:/data
        networks:
            - cake-generator-dev
        restart: unless-stopped
